apiVersion: v1
kind: Service
metadata:
  name: primes-db-service
  labels:
    app: primes-db-service
spec:
  type: LoadBalancer
  ports:
  - port: 30006
    targetPort: 80
    nodePort: 30016
  selector:
    app: primes-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: primes-db
spec:
  selector:
    matchLabels:
      app: primes-db
  template:
    metadata:
      labels:
        app: primes-db
        project: prime-numbers
    spec:
      containers:
      - name: primes-db
        image: primes-db:v1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80